baseurl = "https://geografia-au.github.io/"
languageCode = "en-us"
title = "Geografia: Demography, Economics, Spatial Planning"
theme = "geografia_theme"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

[params]
    viewMorePostLink     = "/blog/"
    author = "geografia"
    description = "[Γε0γραφια] a 3,000 year old discipline that explores the interaction between people and places"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email

    email = "info@geografia.com.au"
    about_us = ""
    copyright = "Copyright (c) 2015 - 2016, Geografia; all rights reserved."
    date_format = "2006-01-02"
    logo = "img/geografia_logo.svg"
    address = "Suite 1, Level 21, 15 Collins St, Melbourne VIC 3000"
    address_map_gist = "//render.githubusercontent.com/view/geojson?enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f676973742f7361626d616e2f64393961353535333738623463383435323839346564636137393233613363622f7261772f373936613835386533396437386635616439613465326232616461366532373263313938326638392f6d61702e67656f6a736f6e#d1934a7c-d14f-447e-9ca6-10a700871df1"
    phone = "+61 3 9329 9004"
    fax = ""

[taxonomies]
  category = "categories"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

[[menu.main]]
    name = "Services"
    url  = "/services"
    weight = 3

[[menu.main]]
    name = "Portfolio"
    url  = "/projects"
    weight = 4

[[menu.main]]
    name = "Contact"
    url  = "/contact"
    weight = 5

[[menu.main]]
    name = "Lab"
    url  = "/lab"
    weight = 6

[[menu.main]]
    name = "Blog"
    url  = "/blog"
    weight = 7

[params.features]
    enable = true
    teaser = "Cities, towns, economies and communities are complex systems. Geografia’s expertise in this field helps clients understand and solve the challenges they face."
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.map]
    enable = true
    title = "Work"
    subtitle = "Geografia works around Australia and in South East Asia. Use the map below to discover a selection of our projects."

[params.recent_posts]
    enable = true
    title = "From our blog"
    subtitle = ""

[params.team]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Our Team"
    subtitle = ""

[params.addresses]
    enable = true
    title = "Contact"
